# Generated by Django 3.1.2 on 2020-10-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormforTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='from_details',
            name='userid',
        ),
    ]
